// ================================================================
// NODE 2: FP CLASSIFIER
// Прості FP правила керуються через Dagobert UI (/fp-rules/).
// Тут залишено лише складну багатопольову логіку.
// ВАЖЛИВО: Always Output Data = OFF
// ================================================================

const alert     = $('DEDUP').first().json;
const rule      = alert.rule  || {};
const eventdata = alert.data?.win?.eventdata || {};
// Syscheck (Wazuh FIM): події цілісності реєстру/файлів (правила 550,554,594,750-752)
// Правило 100743 (Run key/Startup) базується на syscheck, НЕ Sysmon.
// Поля: path, value_name, content_new, content_old, event, diff
const syscheck  = alert.data?.syscheck || alert.alert?.full_alert?.syscheck || {};
const regPath    = (syscheck.path        || '').toLowerCase();
const valueName  = (syscheck.value_name  || '').toLowerCase();
const contentNew = (syscheck.content_new || '').toLowerCase();

const ruleId = String(rule.id    || '');
const level  = Number(rule.level || 0);

function norm(v) { return String(v || '').toLowerCase().replace(/\//g, '\\').trim(); }

const img       = norm(eventdata.image);
const cmd       = norm(eventdata.commandLine);
const srcImg    = norm(eventdata.sourceImage);
const tgtImg    = norm(eventdata.targetImage);
const subjUser  = norm(eventdata.subjectUserName);
const tgtUser   = norm(eventdata.targetUserName);
const tgtDomain = norm(eventdata.targetDomainName || '');
const access    = norm(eventdata.grantedAccess);

// FP правила з Dagobert API (нода Get FP Rules — n8n розбиває масив на items)
const _dynRules = $input.all().map(i => i.json).filter(r => r && r.field);

const NEVER_DROP = new Set([
  '100740','100741','100744','100742','100730','100780','100782','100783','100786','100787',
  '100750','100824','100798','100799','100795','100796','100880','100841','100842','100843','100743','100731',
]);

function classify() {
  // --- Динамічні FP правила з Dagobert API ---
  {
    const _fieldMap = {
      // Sysmon event fields
      image: img, commandLine: cmd, sourceImage: srcImg,
      targetImage: tgtImg, subjectUserName: subjUser,
      targetUserName: tgtUser, grantedAccess: access,
      targetDomainName: tgtDomain,
      imageLoaded:      norm(eventdata.imageLoaded      || ''),
      parentImage:      norm(eventdata.parentImage      || ''),
      parentCommandLine:norm(eventdata.parentCommandLine|| ''),
      startModule:      norm(eventdata.startModule      || ''),
      startFunction:    norm(eventdata.startFunction    || ''),
      destinationIp:    norm(eventdata.destinationIp    || ''),
      destinationPort:  norm(eventdata.destinationPort  || ''),
      // Syscheck / registry
      registryPath:     norm(syscheck.path || ''),
      filePath:         norm(syscheck.path || ''),
      // Wazuh agent metadata
      agentName:        norm(alert.agent?.name || ''),
      agentIp:          norm(alert.agent?.ip   || ''),
    };
    for (const r of _dynRules) {
      if (r.rule_ids && r.rule_ids.length && !r.rule_ids.includes(ruleId)) continue;
      const _v = _fieldMap[r.field] || '';
      const _cv = (r.value || '').toLowerCase();
      let _match = false;
      if      (r.op === 'includes')    _match = _v.includes(_cv);
      else if (r.op === 'endsWith')    _match = _v.endsWith(_cv);
      else if (r.op === 'startsWith')  _match = _v.startsWith(_cv);
      else if (r.op === 'equals')      _match = _v === _cv;
      else if (r.op === 'regex')       _match = new RegExp(r.value, 'i').test(_v);
      if (_match) return { status: r.status || 'FP', reason: '[dyn] ' + (r.reason || 'FP rule') };
    }
  }

  // --- Складна логіка: не виражається одним правилом Dagobert ---

  // 100883: .NET NativeImage (дві умови на полі imageLoaded)
  if (ruleId === '100883') {
    const loadedNorm = norm(eventdata.imageLoaded || '');
    if (loadedNorm.includes('\\nativeimages_') && loadedNorm.endsWith('.ni.dll'))
      return { status: 'FP', reason: '.NET NativeImage (.ni.dll) — unsigned by design, generated by ngen.exe' };
  }

  // 100881: MpCmdRun CtrlRoutine (потребує startFunction + startModule)
  if (ruleId === '100881') {
    if (tgtImg.includes('mpcmdrun.exe')) {
      const startFn  = norm(eventdata.startFunction || '');
      const startMod = norm(eventdata.startModule   || '');
      if (startFn === 'ctrlroutine' && startMod.endsWith('kernelbase.dll'))
        return { status: 'FP', reason: '<unknown>=csrss.exe CtrlRoutine in MpCmdRun — Windows console handler init' };
      return { status: 'FP_CANDIDATE', reason: 'Unknown process → MpCmdRun.exe — possibly AV scan or injection' };
    }
  }

  // 100716: паттерн Acrobat в cmd (умовний, не простий includes)
  if (ruleId === '100716') {
    if (cmd.includes('acrobat') && (cmd.includes('/d') || cmd.includes('/s')))
      return { status: 'FP_CANDIDATE', reason: 'cmd.exe with acrobat reference — verify it is genuine Adobe process' };
  }

  // 100700-702: KMS утиліти (FP_CANDIDATE, потребує перевірки аналітиком)
  if (['100700','100701','100702'].includes(ruleId)) {
    if (cmd.includes('slmgr.vbs')) return { status: 'FP_CANDIDATE', reason: 'slmgr.vbs — Windows KMS licensing tool; verify not part of activation cracker' };
    if (cmd.includes('ospp.vbs'))  return { status: 'FP_CANDIDATE', reason: 'ospp.vbs — Office KMS licensing tool; verify not part of activation cracker' };
  }

  // 100820: обчислювані умови (self-logon, machine account)
  if (ruleId === '100820') {
    if (tgtDomain === 'window manager') return { status: 'FP', reason: 'winlogon.exe DWM session credential — normal Windows session management' };
    if (subjUser && tgtUser && subjUser === tgtUser) return { status: 'FP', reason: 'Machine account self-logon — normal Windows service behavior' };
    if (subjUser.endsWith('$') && tgtUser && !tgtUser.endsWith('$')) return { status: 'FP_CANDIDATE', reason: `Machine account ${subjUser} using explicit creds as user ${tgtUser} — verify` };
  }

  // 100743: Run key / Startup persistence — syscheck (FIM), НЕ Sysmon
  // FP правила в Dagobert обробляють відомо-легітимні записи через поле registryPath.
  // Все що доходить сюди — не спіймано FP правилами → передається аналітику.
  if (ruleId === '100743') {
    const ctx = regPath ? `${regPath} | name=${valueName} | value=${contentNew.slice(0,100)}` : 'no syscheck data';
    return { status: 'PASS', reason: `Run key: ${ctx}` };
  }

  if (ruleId === '100870') return { status: 'PASS', reason: 'PtH candidate — requires Claude context analysis' };
  if (ruleId === '100830') return { status: 'PASS', reason: 'SeDebugPrivilege — no process context, requires Claude analysis' };

  // 100826: перевірка AppData шляху (два поля: image endsWith + image includes path)
  if (ruleId === '100826') {
    const fpImages = ['vibersandbox.exe','nahimicnotifsys.exe','onedrive.exe','onedrivelauncher.exe','onedrivestandaloneupdater.exe','discord.exe','opera.exe','filecoauth.exe','wps.exe','wpscloudsvr.exe'];
    const inAppData = img.includes('\\appdata\\') || img.includes('\\localappdata\\');
    if (inAppData  && fpImages.some(n => img.endsWith('\\' + n) || img.endsWith('/' + n))) return { status: 'FP',           reason: `${img.split('\\').pop()} — known legitimate app from AppData` };
    if (!inAppData && fpImages.some(n => img.endsWith('\\' + n) || img.endsWith('/' + n))) return { status: 'FP_CANDIDATE', reason: `${img.split('\\').pop()} — known app name but unexpected path: ${img}` };
  }

  if (ruleId === '100825') return { status: 'PASS', reason: 'LOLBin network connection — no destination IP in event, needs Claude' };

  // 100740: access mask + source image (два поля)
  if (ruleId === '100740') {
    if (srcImg.endsWith('\\svchost.exe') && access === '0x101000') return { status: 'FP', reason: 'svchost PROCESS_QUERY_LIMITED_INFORMATION on LSASS — normal Windows behavior' };
    return { status: 'PASS', reason: 'LSASS access — requires manual review' };
  }

  return { status: 'PASS', reason: '' };
}

const result = classify();
if (NEVER_DROP.has(ruleId) && result.status === 'FP') { result.status = 'FP_CANDIDATE'; result.reason = '[NEVER_DROP override] ' + result.reason; }

alert.soc = { ...(alert.soc || {}), fp_status: result.status, fp_reason: result.reason, requires_ai_review: result.status !== 'FP' };

if (result.status === 'FP') {
  try {
    const fs = require('fs'); const path = require('path');
    const dir = '/home/node/.n8n/fp-journal';
    fs.mkdirSync(dir, { recursive: true });
    fs.appendFileSync(path.join(dir, 'fp_journal.jsonl'), JSON.stringify({ ts: new Date().toISOString(), source: 'n8n_node2', rule_id: ruleId, level, agent: alert.agent?.name || '', img, cmd, fp_reason: result.reason }) + '\n');
  } catch(e) {}
  return [];
}
return [{ json: alert }];
